name: dio_http_cache
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.0.5

dependencies:
  crypto: ^3.0.3
  dio: ^5.2.1+1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  quiver: ^3.2.1
  sqflite: ^2.2.8+4

dev_dependencies:
  build_runner: ^2.4.6
  lints: ^2.1.1
